import geopandas as gpd
import pandas as pd
import os


# ============================================================
# HSR ROUTE OPTIMIZATION PROJECT
# LULC INTERSECTION ANALYSIS
# ============================================================
#
# Current project assumption:
# Ground footprint = 3.5 m total width
#
# This script:
# 1. Loads the three HSR route corridors
# 2. Loads Bhuvan LULC polygons
# 3. Finds LULC polygons intersecting each route corridor
# 4. Reports candidate polygon counts
#
# NOTE:
# This version does NOT yet calculate Forest/Agriculture/
# Built-up/Wetland/Waterbody area.
# That will be implemented after this intersection is verified.
# ============================================================


# ============================================================
# PROJECT PATHS
# ============================================================

BASE = r"C:\Users\Texaxs\Desktop\hsr-route-optimization"

LULC = (
    r"C:\Users\Texaxs\Downloads\ROUTE_OPT"
    r"\landuseddata\bhuvan 2\bhuvan 2.shp"
)


# ============================================================
# HSR ROUTE CORRIDORS
# ============================================================
#
# These files were generated by:
#
# create_route_corridors.py
#
# using:
#
# GROUND_FOOTPRINT_M = 3.5
# BUFFER_DISTANCE_M = 1.75
#
# Therefore each corridor is 3.5 m wide in total.
# ============================================================

ROUTES = {
    "Route 1": os.path.join(
        BASE,
        "data",
        "processed",
        "Route_1_corridor_3_5m.gpkg"
    ),

    "Route 2": os.path.join(
        BASE,
        "data",
        "processed",
        "Route_2_corridor_3_5m.gpkg"
    ),

    "Route 3": os.path.join(
        BASE,
        "data",
        "processed",
        "Route_3_corridor_3_5m.gpkg"
    ),
}


# ============================================================
# OUTPUT DIRECTORY
# ============================================================

PROCESSED_DIR = os.path.join(
    BASE,
    "data",
    "processed"
)

RESULTS_DIR = os.path.join(
    BASE,
    "data",
    "results"
)

os.makedirs(PROCESSED_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)


# ============================================================
# CRS
# ============================================================
#
# EPSG:32643 = WGS 84 / UTM Zone 43N
#
# This CRS uses metres, which is required for:
# - distance
# - length
# - area
# - 3.5 m corridor calculations
# ============================================================

METRIC_CRS = "EPSG:32643"

DISPLAY_CRS = "EPSG:4326"


# ============================================================
# START
# ============================================================

print("=" * 70)
print("HSR LULC INTERSECTION ANALYSIS")
print("=" * 70)

print("\nProject:")
print(BASE)

print("\nGround footprint assumption:")
print("3.5 m total width")

print("\nMetric CRS:")
print(METRIC_CRS)


# ============================================================
# CHECK ROUTE FILES
# ============================================================

print("\n" + "=" * 70)
print("CHECKING ROUTE CORRIDOR FILES")
print("=" * 70)

for route_name, route_path in ROUTES.items():

    print(f"\n{route_name}")
    print(f"Path: {route_path}")

    if not os.path.exists(route_path):

        raise FileNotFoundError(
            f"\nERROR: Corridor file not found:\n{route_path}\n"
            f"\nRun create_route_corridors.py first."
        )

    print("Status: FOUND")


# ============================================================
# LOAD ROUTE CORRIDORS
# ============================================================

print("\n" + "=" * 70)
print("LOADING ROUTE CORRIDORS")
print("=" * 70)

corridors = {}

for route_name, route_path in ROUTES.items():

    print(f"\nLoading {route_name}...")

    corridor = gpd.read_file(route_path)

    print(
        f"Features loaded: {len(corridor):,}"
    )

    print(
        f"Original CRS: {corridor.crs}"
    )

    # Reproject to metric CRS
    corridor = corridor.to_crs(METRIC_CRS)

    print(
        f"Working CRS: {corridor.crs}"
    )

    # Basic geometry check
    corridor = corridor[
        corridor.geometry.notna()
    ].copy()

    corridor = corridor[
        ~corridor.geometry.is_empty
    ].copy()

    print(
        f"Valid geometries: {len(corridor):,}"
    )

    corridors[route_name] = corridor


# ============================================================
# CALCULATE ROUTE STUDY BOUND
# ============================================================
#
# We create one bounding box around all three corridors.
#
# It will be converted to WGS84 because the source Bhuvan
# dataset is expected to use geographic coordinates.
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING STUDY BOUND")
print("=" * 70)

route_geometries = []

for corridor in corridors.values():

    route_geometries.extend(
        corridor.geometry.tolist()
    )


all_routes = gpd.GeoSeries(
    route_geometries,
    crs=METRIC_CRS
)


study_bounds_wgs84 = (
    all_routes
    .to_crs(DISPLAY_CRS)
    .total_bounds
)


print("\nStudy bounds:")
print(study_bounds_wgs84)


# ============================================================
# CHECK LULC DATASET
# ============================================================

print("\n" + "=" * 70)
print("CHECKING BHUVAN LULC DATASET")
print("=" * 70)

print(f"\nLULC file:")
print(LULC)

if not os.path.exists(LULC):

    raise FileNotFoundError(
        f"\nERROR: LULC dataset not found:\n{LULC}"
    )

print("Status: FOUND")


# ============================================================
# LOAD LULC DATA
# ============================================================
#
# Only DN is loaded because the current Bhuvan class mapping
# has not yet been finalized.
# ============================================================

print("\nLoading Bhuvan LULC polygons...")

lulc = gpd.read_file(
    LULC,
    bbox=tuple(study_bounds_wgs84),
    columns=["DN"]
)

print(
    f"Bhuvan polygons loaded: {len(lulc):,}"
)

print(
    f"Bhuvan CRS: {lulc.crs}"
)


# ============================================================
# REPROJECT LULC
# ============================================================

print("\nReprojecting LULC to metric CRS...")

lulc = lulc.to_crs(METRIC_CRS)

print(
    f"LULC working CRS: {lulc.crs}"
)


# ============================================================
# BASIC LULC VALIDATION
# ============================================================

lulc = lulc[
    lulc.geometry.notna()
].copy()

lulc = lulc[
    ~lulc.geometry.is_empty
].copy()

print(
    f"Valid LULC geometries: {len(lulc):,}"
)

print(
    f"Unique DN values: {lulc['DN'].nunique():,}"
)


# ============================================================
# PROCESS EACH ROUTE
# ============================================================

rows = []

print("\n" + "=" * 70)
print("PROCESSING LULC INTERSECTIONS")
print("=" * 70)


for route_name, corridor in corridors.items():

    print("\n" + "-" * 70)
    print(f"Processing: {route_name}")
    print("-" * 70)

    print(
        f"Corridor features: {len(corridor):,}"
    )


    # --------------------------------------------------------
    # SPATIAL JOIN
    # --------------------------------------------------------
    #
    # We identify LULC polygons that intersect the 3.5 m
    # HSR ground footprint.
    # --------------------------------------------------------

    candidate = gpd.sjoin(
        lulc,
        corridor,
        predicate="intersects",
        how="inner"
    )


    print(
        f"Intersecting LULC polygons: {len(candidate):,}"
    )


    # --------------------------------------------------------
    # UNIQUE DN VALUES
    # --------------------------------------------------------

    unique_dn = candidate["DN"].nunique()

    print(
        f"Unique DN values intersected: {unique_dn:,}"
    )


    # --------------------------------------------------------
    # STORE INTERMEDIATE RESULT
    # --------------------------------------------------------

    rows.append({
        "route": route_name,
        "lulc_candidate_polygons": len(candidate),
        "unique_dn_values": unique_dn
    })


# ============================================================
# CREATE SUMMARY
# ============================================================

out = pd.DataFrame(rows)


# ============================================================
# DISPLAY SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("INTERMEDIATE LULC RESULT")
print("=" * 70)

print(
    out.to_string(index=False)
)


# ============================================================
# SAVE RESULT
# ============================================================

output_file = os.path.join(
    RESULTS_DIR,
    "lulc_intersection_check_3_5m.csv"
)


out.to_csv(
    output_file,
    index=False
)


# ============================================================
# FINISHED
# ============================================================

print("\n" + "=" * 70)
print("ANALYSIS COMPLETE")
print("=" * 70)

print("\nSaved result:")
print(output_file)

print("\n3.5 m corridor successfully used for LULC intersection.")

print("\nNext stage:")
print(
    "Calculate actual Forest, Agriculture, Built-up, "
    "Wetland and Waterbody areas in km²."
)

print("=" * 70)